

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://admin:password@mongodb:27017/cyberguard?authSource=admin
    volumes:
      - .:/app
      - /usr/bin/subfinder:/usr/bin/subfinder
      - /usr/bin/assetfinder:/usr/bin/assetfinder
      - /usr/local/bin/findomain:/usr/bin/findomain
      - /usr/bin/searchsploit:/usr/bin/searchsploit
  mongodb:
    image: mongo:latest
    container_name: cyberguard_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: cyberguard
    command: mongod --wiredTigerCacheSizeGB 1 --logpath /var/log/mongodb/mongod.log --logappend --setParameter logLevel=1
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
