from fastapi import FastAPI, HTTPException
from app.config.log_middleware import LoggingMiddleware

from app.api.requests.request_flow import router as request_flow_router
from app.config.mongodb import db_startup
import logging

logging.getLogger("pymongo").setLevel(logging.WARNING)

app = FastAPI(
    title="CyberGuard PTaaS",
    description="This Swagger documentation is generated by FastAPI",
    lifespan=db_startup,
)


app.include_router(request_flow_router, prefix="/api", tags=["Request Flow"])
app.add_middleware(LoggingMiddleware)

@app.get("/")
async def root():
    return {"message": "Welcome to CyberGuard PTaaS"}


