from fastapi import FastAPI
from app.api.requests.request_flow import router as request_flow_router

app = FastAPI(
    title="CyberGuard PTaaS",
    description="This Swagger documentation is generated by FastAPI",
    debug=True
)


app.include_router(request_flow_router, prefix="/api" , tags=["Request Flow"])

@app.get("/")
async def root():
    return {"message": "Welcome to CyberGuard PTaaS"}

